# Change these first
owner: ks-collab # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Petal Cite Production
    url: https://cite.petal.org/api/status
  - name: Petal Cite Staging
    url: https://cite.petal-dev.org/api/status
  - name: Petal Connect Production
    url: https://connect.petal.org
  - name: Petal Connect Staging
    url: https://connect.petal-dev.org
  - name: Petal Website
    url: https://www.petal.org    
  - name: Grobid service
    url: https://grobid.petal.org/api/isalive
  - name: Grafana service
    url: https://grafana.petal.org    

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://www.petal.org/letterhead/petal-letterhead-quicksand.webp
  name: Petal
  introTitle: "Productivity software for academics"
  introMessage: This page displays the live status of Petal services
  navbar:
    - title: Uptime
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
