# Change these first
owner: ks-collab # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: KaleidoGlobe Production
    url: https://app.kaleidoglobe.com/api/status
  - name: KaleidoGlobe Dev/Staging
    url: https://dev.kaleidoglobe.com/api/status

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://kaleidoglobe-public.s3-us-west-2.amazonaws.com/kaleidoglobe_logo.webp
  name: KaleidoGlobe API
  introTitle: "**KaleidoGlobe** is a cloud-native knowledge management solution built for businesses, research labs, and individuals."
  introMessage: This page displays the live status of the KaleidoGlobe web application
  navbar:
    - title: Uptime
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
