# Change these first
owner: ks-collab # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: KaleidoGlobe API
    url: https://api.kaleidoglobe.com/status

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://kaleidoglobe-public.s3-us-west-2.amazonaws.com/kaleidoglobe_logo.webp
  name: KaleidoGlobe API
  introTitle: "**KaleidoGlobe** is a cloud-native knowledge management solution built for businesses, research labs, and individuals."
  introMessage: This page displays the live status of the KaleidoGlobe API
  navbar:
    - title: Uptime
      href: /upptime
    - title: Status
      href: https://app.kaleidoglobe.com/status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
